### ISSUE TITLE
Concern anout the initialization Snip function

### ISSUE THREAD

**Issue by Shiweiliuiiiiiii** [mi-lad/snip#3]
I noticed that you copy the model and reinitialize it to calculate the gradients in SNIP function by "nn.init.xavier_normal_(layer.weight)". Thus, the initialization used for pruning is not the exact model used for training. Am I right?

**Comment by mil-ad** [comment]
Yes. This is strange but it's actually what the snip paper does if you read it carefully. There's a long discussion about this in the openreview comments.

**Comment by Shiweiliuiiiiiii** [comment]
Thanks for your reply. It is true that Snip can learn architecturally important weights.
